export const FETCH_GEONAMES_REQUEST = "FETCH_GEONAMES_REQUEST";
export const FETCH_GEONAMES_SUCCESS = "FETCH_GEONAMES_SUCCESS";
export const FETCH_GEONAMES_FAILURE = "FETCH_GEONAMES_FAILURE";

export const FETCH_CITY_REQUEST = "FETCH_CITY_REQUEST";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_FAILURE = "FETCH_CITY_FAILURE";

export const FETCH_DETAILS_REQUEST = "FETCH_CITY_DETAILS_REQUEST";
export const FETCH_DETAILS_SUCCESS = "FETCH_CITY_DETAILS_SUCCESS";
export const FETCH_DETAILS_FAILURE = "FETCH_CITY_DETAILS_FAILURE";

export const FETCH_IMAGE_REQUEST = "FETCH_CITY_IMAGE_REQUEST";
export const FETCH_IMAGE_SUCCESS = "FETCH_CITY_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAILURE = "FETCH_CITY_IMAGE_FAILURE";

export const FETCH_CITY_INFO_REQUEST = "FETCH_CITY_INFO_REQUEST";
export const FETCH_CITY_INFO_SUCCESS = "FETCH_CITY_INFO_SUCCESS";
export const FETCH_CITY_INFO_FAILURE = "FETCH_CITY_INFO_FAILURE";

export const FETCH_SALARIES_REQUEST = "FETCH_SALARIES_REQUEST";
export const FETCH_SALARIES_SUCCESS = "FETCH_SALARIES_SUCCESS";
export const FETCH_SALARIES_FAILURE = "FETCH_SALARIES_FAILURE";

export const FETCH_CITY_TAXATION_REQUEST = "FETCH_CITY_TAXATION_REQUEST";
export const FETCH_CITY_TAXATION_SUCCESS = "FETCH_CITY_TAXATION_SUCCESS";
export const FETCH_CITY_TAXATION_FAILURE = "FETCH_CITY_TAXATION_FAILURE";
